pipeline {
    agent any
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t myapp:latest .'
            }
        }

        stage('Run Container') {
            steps {
                // Run the container, mapping port 3000 inside the container to port 8081 on the host machine
                sh 'docker run -d -p 8081:3000 myapp:latest'
            }
        }
    }
}
