pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/your-username/secure-cicd-pipeline.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t myapp:latest .'
            }
        }

        stage('Run Container') {
            steps {
                // Run the container, mapping port 3000 inside the container to port 8081 on the host machine
                sh 'docker run -d -p 8081:3000 myapp:latest'
            }
        }
    }
}
